[build]
  command = "npm install --legacy-peer-deps && npx craco build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
